- include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_service_mgr }}_{{ ansible_distribution }}.yml"
        - "{{ ansible_service_mgr }}.yml"
      paths:
        - "vars"

- lineinfile:
    path: "{{ item.path }}"
    line: "{{ item.line }}"
    create: true
  with_items: [ "{{ etc_lines }}" ]
  become: true

- ini_file:
    path: "{{ item.path }}"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    create: true
  with_items: [ "{{ etc_inis }}" ]
  become: true
